# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_kasir.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QMainWindow
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 60, 481, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 160, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 200, 500, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 280, 260, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_pencarian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pencarian.setGeometry(QtCore.QRect(200, 350, 120, 40))
        self.pushButton_pencarian.setObjectName("pushButton_pencarian")
        self.pushButton_stok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stok.setGeometry(QtCore.QRect(360, 350, 120, 40))
        self.pushButton_stok.setObjectName("pushButton_stok")
        self.pushButton_riwayat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_riwayat.setGeometry(QtCore.QRect(520, 350, 120, 40))
        self.pushButton_riwayat.setObjectName("pushButton_riwayat")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 420, 130, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        # MENGHUBUNGKAN TOMBOL DENGAN FUNGSI
        self.pushButton.clicked.connect(self.mulai_penjualan)
        self.pushButton_pencarian.clicked.connect(self.buka_pencarian)
        self.pushButton_stok.clicked.connect(self.buka_stok)
        self.pushButton_riwayat.clicked.connect(self.buka_riwayat)
        self.pushButton_2.clicked.connect(self.logout)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard Kasir"))
        self.centralwidget.setStyleSheet(_translate("MainWindow", "QWidget#centralwidget { background-color: #E3F2FD; }"))
        self.label.setStyleSheet(_translate("MainWindow", "color: #0D47A1;"))
        self.label.setText(_translate("MainWindow", "DASHBOARD KASIR 🛒"))
        self.label_2.setStyleSheet(_translate("MainWindow", "color: rgba(0, 0, 0, 180);"))
        self.label_2.setText(_translate("MainWindow", "Halo, Kasir!"))
        self.label_3.setStyleSheet(_translate("MainWindow", "color: #1565C0;"))
        self.label_3.setText(_translate("MainWindow", "Selamat Datang di Sistem Penjualan Cepat."))
        self.pushButton.setStyleSheet(_translate("MainWindow", "QPushButton { background-color: #4CAF50; color: white; border: none; border-radius: 10px; padding: 10px 20px; font: 700 14pt \"Times New Roman\";} QPushButton:hover { background-color: #388E3C;}"))
        self.pushButton.setText(_translate("MainWindow", "Mulai Penjualan Baru"))
        self.pushButton_pencarian.setStyleSheet(_translate("MainWindow", "QPushButton { background-color: #9C27B0; color: white; border: none; border-radius: 8px; padding: 10px; font: 600 10pt \"Times New Roman\";} QPushButton:hover { background-color: #7B1FA2;}"))
        self.pushButton_pencarian.setText(_translate("MainWindow", "Cari Barang"))
        self.pushButton_stok.setStyleSheet(_translate("MainWindow", "QPushButton { background-color: #FF9800; color: white; border: none; border-radius: 8px; padding: 10px; font: 600 10pt \"Times New Roman\";} QPushButton:hover { background-color: #F57C00;}"))
        self.pushButton_stok.setText(_translate("MainWindow", "Data Stok"))
        self.pushButton_riwayat.setStyleSheet(_translate("MainWindow", "QPushButton { background-color: #607D8B; color: white; border: none; border-radius: 8px; padding: 10px; font: 600 10pt \"Times New Roman\";} QPushButton:hover { background-color: #455A64;}"))
        self.pushButton_riwayat.setText(_translate("MainWindow", "Riwayat"))
        self.pushButton_2.setStyleSheet(_translate("MainWindow", "QPushButton { background-color: #FF7043; color: white; border: none; border-radius: 8px; padding: 10px; font: 600 11pt \"Times New Roman\";} QPushButton:hover { background-color: #F4511E;}"))
        self.pushButton_2.setText(_translate("MainWindow", "Logout"))

    # ============= FUNGSI LOGIKA (FINAL) =============

    def mulai_penjualan(self):
        """Buka halaman penjualan baru"""
        try:
            from halaman_penjualan_baru import HalamanPenjualanBaru
            self.win_penjualan = HalamanPenjualanBaru()
            self.win_penjualan.show()
        except Exception as e:
            QMessageBox.critical(None, "Error", f"Gagal membuka halaman penjualan:\n{e}")

    def buka_pencarian(self):
        """Buka halaman pencarian barang"""
        try:
            from halaman_cari_barang import HalamanCariBarang
            self.win_cari = HalamanCariBarang()
            self.win_cari.show()
        except Exception as e:
            QMessageBox.critical(None, "Error", f"Gagal membuka halaman pencarian:\n{e}")

    def buka_stok(self):
        """Buka halaman data stok"""
        try:
            from data_stok import DataStokWindow
            self.win_stok = DataStokWindow()
            self.win_stok.show()
        except Exception as e:
            QMessageBox.critical(None, "Error", f"Gagal membuka data stok:\n{e}")

    def buka_riwayat(self):
        """Buka halaman riwayat transaksi"""
        try:
            from riwayat_transaksi import RiwayatTransaksiWindow
            self.win_riwayat = RiwayatTransaksiWindow()
            self.win_riwayat.show()
        except Exception as e:
            QMessageBox.critical(None, "Error", f"Gagal membuka riwayat transaksi:\n{e}")

    def logout(self):
        reply = QMessageBox.question(
            None,
            "Konfirmasi",
            "Yakin ingin logout?",
            QMessageBox.Yes | QMessageBox.No
        )

        if reply == QMessageBox.Yes:
            try:
                from form_login import LoginWindow
                self.form_login = LoginWindow()
                self.form_login.show()

                QtWidgets.QApplication.activeWindow().close()
            except Exception as e:
                QMessageBox.critical(None, "Error", f"Gagal logout:\n{e}")


class MainWindow(QMainWindow):
    """Window Dashboard"""
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.nama_kasir = "Kasir"
        self.update_greeting()
    
    def update_greeting(self):
        self.ui.label_2.setText(f"Halo, {self.nama_kasir}!")
    
    def set_nama_kasir(self, nama):
        self.nama_kasir = nama
        self.update_greeting()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())
