# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bntr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from jenis import Jenis
from ukuran import Ukuran
from barang import Barang
from PyQt5 import QtCore, QtGui, QtWidgets
import form_dashboard_admin as back
from PyQt5.QtWidgets import QMessageBox
import Icon.Icon_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 729)
        MainWindow.setMinimumSize(QtCore.QSize(1180, 729))
        MainWindow.setMaximumSize(QtCore.QSize(1180, 729))
        MainWindow.setStyleSheet("QMainWindow, QWidget#centralWidget {\n"
"    background-color:rgb(238, 238, 238);\n"
"}\n"
"QLineEdit {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            background-color: white;\n"
"        }\n"
"QTableWidget {\n"
"            border: 1px solid #ddd;\n"
"            background-color: white;\n"
"            border-radius: 8px;\n"
"            selection-background-color: #e0f7fa; /* Warna highlight baris */\n"
"        }\n"
"        QHeaderView::section {\n"
"            background-color: white;\n"
"            padding: 10px;\n"
"            font-weight: bold;\n"
"            border-top: none;\n"
"            border-bottom: 2px solid #ddd;\n"
"        }\n"
"QHeaderView::section:first-child {\n"
"    border-top-left-radius: 0px;\n"
"}\n"
"QHeaderView::section:last-child {\n"
"    border-top-right-radius: 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1191, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"    background-color: #495057;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    padding: 15px 15px 10px 15px;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnKembali = QtWidgets.QPushButton(self.centralwidget)
        self.btnKembali.setGeometry(QtCore.QRect(10, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnKembali.setFont(font)
        self.btnKembali.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #ecf0f1;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"}\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 5px;\n"
"}")
        self.btnKembali.setObjectName("btnKembali")
        self.tableStok = QtWidgets.QTableWidget(self.centralwidget)
        self.tableStok.setGeometry(QtCore.QRect(20, 160, 731, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableStok.sizePolicy().hasHeightForWidth())
        self.tableStok.setSizePolicy(sizePolicy)
        self.tableStok.setMinimumSize(QtCore.QSize(1, 531))
        self.tableStok.setMaximumSize(QtCore.QSize(931, 1111111))
        self.tableStok.setStyleSheet("")
        self.tableStok.setDragEnabled(True)
        self.tableStok.setAlternatingRowColors(False)
        self.tableStok.setGridStyle(QtCore.Qt.SolidLine)
        self.tableStok.setObjectName("tableStok")
        self.tableStok.setColumnCount(6)
        self.tableStok.setRowCount(0)
        self.tableStok.verticalHeader().setVisible(False)
        self.tableStok.setColumnWidth(0, 105)
        self.tableStok.setColumnWidth(1, 120)
        self.tableStok.setColumnWidth(2, 160)
        self.tableStok.setColumnWidth(3, 115)
        self.tableStok.setColumnWidth(4, 114)
        self.tableStok.setColumnWidth(5, 115)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableStok.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableStok.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableStok.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStok.setHorizontalHeaderItem(5, item)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 80, 731, 80))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1111111))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-top-right-radius:8px;\n"
"border-top-left-radius:8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"border-radius: 0px; \n"
"background-color: transparent;\n"
"color: rgb(134, 134, 134);\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:8px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(580, 20, 128, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            background-color: #ffffff;\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(450, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            background-color: #ffffff;\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(752, 80, 420, 631))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-radius:8px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 401, 611))
        self.frame_6.setStyleSheet("border: None;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_6)
        self.tabWidget.setGeometry(QtCore.QRect(0, 5, 411, 622))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    left: 0px; \n"
"}\n"
"QTabBar::tab {\n"
"    background: #495057;\n"
"    color: #ffffff;\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 4px;\n"
"    padding: 10px 15px;\n"
"    margin: 5px 2px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    color: #000000;\n"
"    border-color: #ddd;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tabAdd = QtWidgets.QWidget()
        self.tabAdd.setStyleSheet("QTabWidget:Header {\n"
"    background-color: rgb(255, 1, 5);\n"
"}")
        self.tabAdd.setObjectName("tabAdd")
        self.frame_2 = QtWidgets.QFrame(self.tabAdd)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 401, 541))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-radius:8px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labelID = QtWidgets.QLabel(self.frame_2)
        self.labelID.setGeometry(QtCore.QRect(20, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelID.setFont(font)
        self.labelID.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelID.setObjectName("labelID")
        self.txtID = QtWidgets.QLineEdit(self.frame_2)
        self.txtID.setGeometry(QtCore.QRect(20, 35, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtID.setFont(font)
        self.txtID.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;")
        self.txtID.setObjectName("txtID")
        self.labelJenis = QtWidgets.QLabel(self.frame_2)
        self.labelJenis.setGeometry(QtCore.QRect(20, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelJenis.setFont(font)
        self.labelJenis.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelJenis.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJenis.setObjectName("labelJenis")
        self.cmbJenis = QtWidgets.QComboBox(self.frame_2)
        self.cmbJenis.setGeometry(QtCore.QRect(20, 110, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbJenis.setFont(font)
        self.cmbJenis.setStyleSheet("QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbJenis.setPlaceholderText("")
        self.cmbJenis.setObjectName("cmbJenis")
        self.cmbJenis.addItem("")
        self.labelNama = QtWidgets.QLabel(self.frame_2)
        self.labelNama.setGeometry(QtCore.QRect(20, 150, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNama.setFont(font)
        self.labelNama.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelNama.setObjectName("labelNama")
        self.txtNama = QtWidgets.QLineEdit(self.frame_2)
        self.txtNama.setGeometry(QtCore.QRect(20, 190, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtNama.setFont(font)
        self.txtNama.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;")
        self.txtNama.setObjectName("txtNama")
        self.labelUkuran = QtWidgets.QLabel(self.frame_2)
        self.labelUkuran.setGeometry(QtCore.QRect(20, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUkuran.setFont(font)
        self.labelUkuran.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelUkuran.setObjectName("labelUkuran")
        self.labelStok = QtWidgets.QLabel(self.frame_2)
        self.labelStok.setGeometry(QtCore.QRect(20, 310, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStok.setFont(font)
        self.labelStok.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelStok.setObjectName("labelStok")
        self.cmbUkuran = QtWidgets.QComboBox(self.frame_2)
        self.cmbUkuran.setGeometry(QtCore.QRect(20, 270, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbUkuran.setFont(font)
        self.cmbUkuran.setStyleSheet("QLineEdit, QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"            background-color: white;\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbUkuran.setEditable(False)
        self.cmbUkuran.setPlaceholderText("")
        self.cmbUkuran.setFrame(False)
        self.cmbUkuran.setObjectName("cmbUkuran")
        self.cmbUkuran.addItem("")
        self.txtStok = QtWidgets.QLineEdit(self.frame_2)
        self.txtStok.setGeometry(QtCore.QRect(20, 350, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtStok.setFont(font)
        self.txtStok.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;")
        self.txtStok.setObjectName("txtStok")
        self.labelHarga = QtWidgets.QLabel(self.frame_2)
        self.labelHarga.setGeometry(QtCore.QRect(20, 390, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelHarga.setFont(font)
        self.labelHarga.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelHarga.setObjectName("labelHarga")
        self.txtHarga = QtWidgets.QLineEdit(self.frame_2)
        self.txtHarga.setGeometry(QtCore.QRect(20, 430, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtHarga.setFont(font)
        self.txtHarga.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;")
        self.txtHarga.setObjectName("txtHarga")
        self.btnSimpan = QtWidgets.QPushButton(self.frame_2)
        self.btnSimpan.setGeometry(QtCore.QRect(20, 485, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSimpan.setFont(font)
        self.btnSimpan.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton#btnSimpan {\n"
"    background-color: #4A90E2;\n"
"}\n"
"QPushButton#btnSimpan:hover {\n"
"    background-color: #5D9CEC;\n"
"}")
        self.btnSimpan.setObjectName("btnSimpan")
        self.labelID.raise_()
        self.labelJenis.raise_()
        self.labelNama.raise_()
        self.labelUkuran.raise_()
        self.labelHarga.raise_()
        self.labelStok.raise_()
        self.btnSimpan.raise_()
        self.txtStok.raise_()
        self.txtHarga.raise_()
        self.cmbUkuran.raise_()
        self.txtNama.raise_()
        self.cmbJenis.raise_()
        self.txtID.raise_()
        self.tabWidget.addTab(self.tabAdd, "")
        self.tabEdit = QtWidgets.QWidget()
        self.tabEdit.setObjectName("tabEdit")
        self.frame_3 = QtWidgets.QFrame(self.tabEdit)
        self.frame_3.setGeometry(QtCore.QRect(0, 82, 401, 469))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-bottom-right-radius:8px;\n"
"border-bottom-left-radius:8px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.txtHarga_2 = QtWidgets.QLineEdit(self.frame_3)
        self.txtHarga_2.setGeometry(QtCore.QRect(20, 358, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtHarga_2.setFont(font)
        self.txtHarga_2.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
" border-radius: 8px;")
        self.txtHarga_2.setObjectName("txtHarga_2")
        self.labelJenis_2 = QtWidgets.QLabel(self.frame_3)
        self.labelJenis_2.setGeometry(QtCore.QRect(21, 4, 41, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelJenis_2.setFont(font)
        self.labelJenis_2.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);\n"
"")
        self.labelJenis_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelJenis_2.setObjectName("labelJenis_2")
        self.cmbUkuran_2 = QtWidgets.QComboBox(self.frame_3)
        self.cmbUkuran_2.setGeometry(QtCore.QRect(20, 198, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbUkuran_2.setFont(font)
        self.cmbUkuran_2.setStyleSheet("QLineEdit, QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"            background-color: white;\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbUkuran_2.setEditable(False)
        self.cmbUkuran_2.setPlaceholderText("")
        self.cmbUkuran_2.setFrame(False)
        self.cmbUkuran_2.setObjectName("cmbUkuran_2")
        self.cmbUkuran_2.addItem("")
        self.labelStok_2 = QtWidgets.QLabel(self.frame_3)
        self.labelStok_2.setGeometry(QtCore.QRect(20, 238, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStok_2.setFont(font)
        self.labelStok_2.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelStok_2.setObjectName("labelStok_2")
        self.labelNama_2 = QtWidgets.QLabel(self.frame_3)
        self.labelNama_2.setGeometry(QtCore.QRect(20, 78, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNama_2.setFont(font)
        self.labelNama_2.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);\n"
"")
        self.labelNama_2.setObjectName("labelNama_2")
        self.labelHarga_2 = QtWidgets.QLabel(self.frame_3)
        self.labelHarga_2.setGeometry(QtCore.QRect(20, 318, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelHarga_2.setFont(font)
        self.labelHarga_2.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelHarga_2.setObjectName("labelHarga_2")
        self.labelUkuran_2 = QtWidgets.QLabel(self.frame_3)
        self.labelUkuran_2.setGeometry(QtCore.QRect(20, 158, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUkuran_2.setFont(font)
        self.labelUkuran_2.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelUkuran_2.setObjectName("labelUkuran_2")
        self.txtStok_2 = QtWidgets.QLineEdit(self.frame_3)
        self.txtStok_2.setGeometry(QtCore.QRect(20, 278, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtStok_2.setFont(font)
        self.txtStok_2.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
" border-radius: 8px;")
        self.txtStok_2.setObjectName("txtStok_2")
        self.cmbJenis_2 = QtWidgets.QComboBox(self.frame_3)
        self.cmbJenis_2.setGeometry(QtCore.QRect(20, 38, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbJenis_2.setFont(font)
        self.cmbJenis_2.setStyleSheet("QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbJenis_2.setPlaceholderText("")
        self.cmbJenis_2.setObjectName("cmbJenis_2")
        self.cmbJenis_2.addItem("")
        self.txtNama_2 = QtWidgets.QLineEdit(self.frame_3)
        self.txtNama_2.setGeometry(QtCore.QRect(20, 118, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtNama_2.setFont(font)
        self.txtNama_2.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
"border-radius: 8px;")
        self.txtNama_2.setObjectName("txtNama_2")
        self.btnUpdate_2 = QtWidgets.QPushButton(self.frame_3)
        self.btnUpdate_2.setGeometry(QtCore.QRect(20, 413, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnUpdate_2.setFont(font)
        self.btnUpdate_2.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: #6C757D;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #868E96;\n"
"}\n"
"")
        self.btnUpdate_2.setObjectName("btnUpdate_2")
        self.labelJenis_2.raise_()
        self.labelUkuran_2.raise_()
        self.labelStok_2.raise_()
        self.labelHarga_2.raise_()
        self.txtHarga_2.raise_()
        self.cmbUkuran_2.raise_()
        self.labelNama_2.raise_()
        self.txtStok_2.raise_()
        self.cmbJenis_2.raise_()
        self.txtNama_2.raise_()
        self.btnUpdate_2.raise_()
        self.frame_4 = QtWidgets.QFrame(self.tabEdit)
        self.frame_4.setGeometry(QtCore.QRect(0, 10, 400, 71))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-top-right-radius:8px;\n"
"border-top-left-radius:8px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(25, 0, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;\n"
"border-radius: 0px; \n"
"background-color: transparent;\n"
"color: rgb(134, 134, 134);\n"
"")
        self.label_4.setObjectName("label_4")
        self.txtID_2 = QtWidgets.QLineEdit(self.frame_4)
        self.txtID_2.setGeometry(QtCore.QRect(20, 20, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtID_2.setFont(font)
        self.txtID_2.setStyleSheet("border-top-left-radius:8px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-left-radius:8px;\n"
"border-bottom-right-radius:0px;\n"
"color: rgb(68, 68, 68);\n"
"padding:8px;")
        self.txtID_2.setText("")
        self.txtID_2.setObjectName("txtID_2")
        self.btnCari = QtWidgets.QPushButton(self.frame_4)
        self.btnCari.setGeometry(QtCore.QRect(340, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCari.setFont(font)
        self.btnCari.setStyleSheet("QPushButton {\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.btnCari.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Search/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnCari.setIcon(icon)
        self.btnCari.setIconSize(QtCore.QSize(23, 23))
        self.btnCari.setObjectName("btnCari")
        self.tabWidget.addTab(self.tabEdit, "")
        self.tabDelete = QtWidgets.QWidget()
        self.tabDelete.setObjectName("tabDelete")
        self.frame_7 = QtWidgets.QFrame(self.tabDelete)
        self.frame_7.setGeometry(QtCore.QRect(0, 82, 401, 469))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-bottom-right-radius:8px;\n"
"border-bottom-left-radius:8px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.txtHarga_3 = QtWidgets.QLineEdit(self.frame_7)
        self.txtHarga_3.setGeometry(QtCore.QRect(20, 358, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtHarga_3.setFont(font)
        self.txtHarga_3.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
" border-radius: 8px;")
        self.txtHarga_3.setObjectName("txtHarga_3")
        self.labelJenis_3 = QtWidgets.QLabel(self.frame_7)
        self.labelJenis_3.setGeometry(QtCore.QRect(21, 4, 41, 29))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelJenis_3.setFont(font)
        self.labelJenis_3.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);\n"
"")
        self.labelJenis_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelJenis_3.setObjectName("labelJenis_3")
        self.cmbUkuran_3 = QtWidgets.QComboBox(self.frame_7)
        self.cmbUkuran_3.setGeometry(QtCore.QRect(20, 198, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbUkuran_3.setFont(font)
        self.cmbUkuran_3.setStyleSheet("QLineEdit, QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"            background-color: white;\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbUkuran_3.setEditable(False)
        self.cmbUkuran_3.setPlaceholderText("")
        self.cmbUkuran_3.setFrame(False)
        self.cmbUkuran_3.setObjectName("cmbUkuran_3")
        self.cmbUkuran_3.addItem("")
        self.labelStok_3 = QtWidgets.QLabel(self.frame_7)
        self.labelStok_3.setGeometry(QtCore.QRect(20, 238, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStok_3.setFont(font)
        self.labelStok_3.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelStok_3.setObjectName("labelStok_3")
        self.labelNama_3 = QtWidgets.QLabel(self.frame_7)
        self.labelNama_3.setGeometry(QtCore.QRect(20, 78, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelNama_3.setFont(font)
        self.labelNama_3.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);\n"
"")
        self.labelNama_3.setObjectName("labelNama_3")
        self.labelHarga_3 = QtWidgets.QLabel(self.frame_7)
        self.labelHarga_3.setGeometry(QtCore.QRect(20, 318, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelHarga_3.setFont(font)
        self.labelHarga_3.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelHarga_3.setObjectName("labelHarga_3")
        self.labelUkuran_3 = QtWidgets.QLabel(self.frame_7)
        self.labelUkuran_3.setGeometry(QtCore.QRect(20, 158, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelUkuran_3.setFont(font)
        self.labelUkuran_3.setStyleSheet("border: None;\n"
"color: rgb(68, 68, 68);")
        self.labelUkuran_3.setObjectName("labelUkuran_3")
        self.txtStok_3 = QtWidgets.QLineEdit(self.frame_7)
        self.txtStok_3.setGeometry(QtCore.QRect(20, 278, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtStok_3.setFont(font)
        self.txtStok_3.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
" border-radius: 8px;")
        self.txtStok_3.setObjectName("txtStok_3")
        self.cmbJenis_3 = QtWidgets.QComboBox(self.frame_7)
        self.cmbJenis_3.setGeometry(QtCore.QRect(20, 38, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmbJenis_3.setFont(font)
        self.cmbJenis_3.setStyleSheet("QComboBox {\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            color: rgb(68, 68, 68);\n"
"        }\n"
"        QComboBox::drop-down {\n"
"            border: 0px; \n"
"        }")
        self.cmbJenis_3.setPlaceholderText("")
        self.cmbJenis_3.setObjectName("cmbJenis_3")
        self.cmbJenis_3.addItem("")
        self.txtNama_3 = QtWidgets.QLineEdit(self.frame_7)
        self.txtNama_3.setGeometry(QtCore.QRect(20, 118, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtNama_3.setFont(font)
        self.txtNama_3.setStyleSheet("border :1px solid #c5c5c5;\n"
"padding:8px;\n"
"border-radius: 8px;")
        self.txtNama_3.setObjectName("txtNama_3")
        self.btnDelete = QtWidgets.QPushButton(self.frame_7)
        self.btnDelete.setGeometry(QtCore.QRect(20, 413, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"    background-color: #DC3545;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #E64A5A;\n"
"}")
        self.btnDelete.setObjectName("btnDelete")
        self.labelUkuran_3.raise_()
        self.labelHarga_3.raise_()
        self.labelStok_3.raise_()
        self.txtHarga_3.raise_()
        self.labelJenis_3.raise_()
        self.cmbUkuran_3.raise_()
        self.labelNama_3.raise_()
        self.txtStok_3.raise_()
        self.cmbJenis_3.raise_()
        self.txtNama_3.raise_()
        self.btnDelete.raise_()
        self.frame_8 = QtWidgets.QFrame(self.tabDelete)
        self.frame_8.setGeometry(QtCore.QRect(0, 10, 400, 71))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #ddd;\n"
"border-top-right-radius:8px;\n"
"border-top-left-radius:8px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setGeometry(QtCore.QRect(25, 0, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\n"
"border-radius: 0px; \n"
"background-color: transparent;\n"
"color: rgb(134, 134, 134);\n"
"")
        self.label_5.setObjectName("label_5")
        self.txtID_3 = QtWidgets.QLineEdit(self.frame_8)
        self.txtID_3.setGeometry(QtCore.QRect(20, 20, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.txtID_3.setFont(font)
        self.txtID_3.setStyleSheet("border-top-left-radius:8px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-left-radius:8px;\n"
"border-bottom-right-radius:0px;\n"
"color: rgb(68, 68, 68);\n"
"padding:8px;")
        self.txtID_3.setText("")
        self.txtID_3.setObjectName("txtID_3")
        self.btnCari_2 = QtWidgets.QPushButton(self.frame_8)
        self.btnCari_2.setGeometry(QtCore.QRect(340, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCari_2.setFont(font)
        self.btnCari_2.setStyleSheet("QPushButton {\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-left-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
        self.btnCari_2.setText("")
        self.btnCari_2.setIcon(icon)
        self.btnCari_2.setIconSize(QtCore.QSize(23, 23))
        self.btnCari_2.setObjectName("btnCari_2")
        self.tabWidget.addTab(self.tabDelete, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.load_table()
        self.getDataJenis()
        self.getDataUkuran()
        self.btnSimpan.clicked.connect(self.Simpan)
        self.btnCari.clicked.connect(self.CariData)
        self.btnCari_2.clicked.connect(self.CariData)
        self.btnUpdate_2.clicked.connect(self.UpdateData)
        self.btnDelete.clicked.connect(self.DeleteData)
        self.lineEdit.textChanged.connect(self.filter_search)
        self.comboBox_3.currentIndexChanged.connect(self.filter_search)
        self.comboBox_2.currentIndexChanged.connect(self.filter_search)
        self.btnKembali.clicked.connect(self.kembali)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kelola Data Pakaian"))
        self.btnKembali.setText(_translate("MainWindow", "⬅️ Kembali"))
        item = self.tableStok.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableStok.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jenis"))
        item = self.tableStok.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nama Pakaian"))
        item = self.tableStok.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ukuran"))
        item = self.tableStok.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Stok"))
        item = self.tableStok.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Harga"))
        self.label_2.setText(_translate("MainWindow", "Search"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Cari berdasarkan id atau nama pakaian.."))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Filter Ukuran"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Filter Jenis"))
        self.labelID.setText(_translate("MainWindow", "ID Barang"))
        self.txtID.setPlaceholderText(_translate("MainWindow", "Masukkan ID "))
        self.labelJenis.setText(_translate("MainWindow", "Jenis"))
        self.cmbJenis.setItemText(0, _translate("MainWindow", "Pilih Jenis"))
        self.labelNama.setText(_translate("MainWindow", "Nama Barang"))
        self.txtNama.setPlaceholderText(_translate("MainWindow", "Masukkan Nama "))
        self.labelUkuran.setText(_translate("MainWindow", "Ukuran"))
        self.labelStok.setText(_translate("MainWindow", "Stok"))
        self.cmbUkuran.setItemText(0, _translate("MainWindow", "Pilih Ukuran"))
        self.txtStok.setPlaceholderText(_translate("MainWindow", "Masukkan Jumlah Stok"))
        self.labelHarga.setText(_translate("MainWindow", "Harga"))
        self.txtHarga.setPlaceholderText(_translate("MainWindow", "Masukkan Harga Barang"))
        self.btnSimpan.setText(_translate("MainWindow", "Simpan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdd), _translate("MainWindow", "Add"))
        self.txtHarga_3.setPlaceholderText(_translate("MainWindow", "Masukkan Harga Barang"))
        self.labelJenis_3.setText(_translate("MainWindow", "Jenis"))
        self.cmbUkuran_3.setItemText(0, _translate("MainWindow", "Pilih Ukuran"))
        self.labelStok_3.setText(_translate("MainWindow", "Stok"))
        self.labelNama_3.setText(_translate("MainWindow", "Nama Barang"))
        self.labelHarga_3.setText(_translate("MainWindow", "Harga"))
        self.labelUkuran_3.setText(_translate("MainWindow", "Ukuran"))
        self.txtStok_3.setPlaceholderText(_translate("MainWindow", "Masukkan Jumlah Stok"))
        self.cmbJenis_3.setItemText(0, _translate("MainWindow", "Pilih Jenis"))
        self.txtNama_3.setPlaceholderText(_translate("MainWindow", "Masukkan Nama "))
        self.btnDelete.setText(_translate("MainWindow", "Hapus"))
        self.label_5.setText(_translate("MainWindow", "Search"))
        self.txtID_3.setPlaceholderText(_translate("MainWindow", "Masukkan id barang yang dicari.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDelete), _translate("MainWindow", "Delete"))
        self.txtHarga_2.setPlaceholderText(_translate("MainWindow", "Masukkan Harga Barang"))
        self.labelJenis_2.setText(_translate("MainWindow", "Jenis"))
        self.cmbUkuran_2.setItemText(0, _translate("MainWindow", "Pilih Ukuran"))
        self.labelStok_2.setText(_translate("MainWindow", "Stok"))
        self.labelNama_2.setText(_translate("MainWindow", "Nama Barang"))
        self.labelHarga_2.setText(_translate("MainWindow", "Harga"))
        self.labelUkuran_2.setText(_translate("MainWindow", "Ukuran"))
        self.txtStok_2.setPlaceholderText(_translate("MainWindow", "Masukkan Jumlah Stok"))
        self.cmbJenis_2.setItemText(0, _translate("MainWindow", "Pilih Jenis"))
        self.txtNama_2.setPlaceholderText(_translate("MainWindow", "Masukkan Nama "))
        self.btnUpdate_2.setText(_translate("MainWindow", "Update"))
        self.label_4.setText(_translate("MainWindow", "Search"))
        self.txtID_2.setPlaceholderText(_translate("MainWindow", "Masukkan id barang yang dicari.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEdit), _translate("MainWindow", "Edit"))

    def getDataJenis(self):
        data=Jenis.select_data()
        self.cmbJenis.addItems(data)
        self.cmbJenis_2.addItems(data)
        self.cmbJenis_3.addItems(data)
        self.comboBox_3.addItems(data)

    def getDataUkuran(self):
        data=Ukuran.select_data()
        self.cmbUkuran.addItems(data)
        self.cmbUkuran_2.addItems(data)
        self.cmbUkuran_3.addItems(data)
        self.comboBox_2.addItems(data)
    
    def filter_search(self):
        search = self.lineEdit.text().lower()
        jenis_filter = self.comboBox_3.currentText().lower()
        ukuran_filter = self.comboBox_2.currentText().lower()

        for row in range(self.tableStok.rowCount()):
            id_item = self.tableStok.item(row, 0)
            jenis_item = self.tableStok.item(row, 1)
            nama_item = self.tableStok.item(row, 2)
            ukuran_item = self.tableStok.item(row, 3)

            id_text = id_item.text().lower() if id_item else ""
            jenis_text = jenis_item.text().lower() if jenis_item else ""
            nama_text = nama_item.text().lower() if nama_item else ""
            ukuran_text = ukuran_item.text().lower() if ukuran_item else ""
            cocok = True

            if search and search not in id_text and search not in nama_text:
                cocok = False
            if jenis_filter != "filter jenis" and jenis_filter != jenis_text:
                cocok = False
            if ukuran_filter != "filter ukuran" and ukuran_filter != ukuran_text:
                cocok = False

            self.tableStok.setRowHidden(row, not cocok)


    def Simpan(self):
        id_barang = self.txtID.text()
        jenis = self.cmbJenis.currentText()
        nama_barang = self.txtNama.text()
        ukuran = self.cmbUkuran.currentText()
        stok = self.txtStok.text()
        harga = self.txtHarga.text()
        try:
            if id_barang == "" or jenis == "Pilih Jenis" or nama_barang == "" or ukuran == "Pilih Ukuran" or stok == "" or harga == "":
                QMessageBox.warning(None, "Error", "Data tidak boleh ada yang kosong!")
                return
            
            elif Barang.cek_id_ada(id_barang):
                QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "ID sudah terpakai!")
                return
            
            elif Barang.cek_nama_ada(nama_barang):
                QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "Nama barang sudah digunakan!")
                return
            
            Barang.insert_data(id_barang, jenis, nama_barang, ukuran, stok, harga)
            QMessageBox.information(None, "Sukses", "Data telah berhasil ditambahkan!")
            self.load_table()
            self.txtID.clear()
            self.cmbJenis.setCurrentIndex(0)
            self.txtNama.clear()
            self.cmbUkuran.setCurrentIndex(0)
            self.txtStok.clear()
            self.txtHarga.clear()
        except Exception as e:
            QMessageBox.critical(self.centralwidget, "Error", f"Terjadi kesalahan: {e}!")

    def load_table(self):
        data = Barang.tampil_data()
        self.tableStok.setRowCount(len(data))

        kolom_center = [0, 3, 4, 5]

        for r, row in enumerate(data):
            for c, val in enumerate(row):
                item = QtWidgets.QTableWidgetItem(str(val))
                if c in kolom_center:
                    item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableStok.setItem(r, c, item)

    def CariData(self):
        id_barang=self.txtID_2.text() or self.txtID_3.text()
        if id_barang == "":
            QMessageBox.warning(self.centralwidget, "Error", "Harap masukkan username!")
            return
        data=Barang.select_data_by_id(id_barang)
        if not data:
            QMessageBox.warning(self.centralwidget, "Error", "Username tidak ditemukan!")
        else:
            jenis=data[1]
            nama=data[2]
            ukuran=data[3]
            stok=data[4]
            harga=data[5]
            self.cmbJenis_2.setCurrentText(str(jenis))
            self.cmbJenis_3.setCurrentText(str(jenis))
            self.txtNama_2.setText(str(nama))
            self.txtNama_3.setText(str(nama))
            self.cmbUkuran_2.setCurrentText(str(ukuran))
            self.cmbUkuran_3.setCurrentText(str(ukuran))
            self.txtStok_2.setText(str(stok))
            self.txtStok_3.setText(str(stok))
            self.txtHarga_2.setText(str(harga))
            self.txtHarga_3.setText(str(harga))
    
    def UpdateData(self):
        id_baru = self.txtID_2.text()
        jenis_baru = self.cmbJenis_2.currentText()
        nama_baru = self.txtNama_2.text()
        ukuran_baru = self.cmbUkuran_2.currentText()
        stok_baru = self.txtStok_2.text()
        harga_baru = self.txtHarga_2.text()
        try:
            if nama_baru == "" or stok_baru == "" or harga_baru == "":
                QMessageBox.warning(None, "Error", "Data tidak boleh ada yang kosong!")
                return
            
            Barang.update_data(jenis_baru, nama_baru, ukuran_baru, stok_baru, harga_baru,id_baru)
            QMessageBox.information(self.centralwidget, "Sukses", "Data berhasil diupdate!")
            self.load_table()
            self.txtID_2.clear()
            self.cmbJenis_2.setCurrentIndex(0)
            self.txtNama_2.clear()
            self.cmbUkuran_2.setCurrentIndex(0)
            self.txtStok_2.clear()
            self.txtHarga_2.clear()

        except Exception as e:
            QMessageBox.critical(self.centralwidget, "Error", f"Terjadi kesalahan: {e}!")
        

    def DeleteData(self):
        try:
            id_barang=self.txtID_3.text()
            data=Barang.select_data_by_id(id_barang)
            nama=data[2]
            reply = QMessageBox.question(self.centralwidget, "Konfirmasi", 
                f"Yakin ingin menghapus data {nama}?",
                QMessageBox.Yes | QMessageBox.No)
            
            if reply == QMessageBox.Yes:
                Barang.delete_data(id_barang)
                QMessageBox.information(self.centralwidget, "Sukses", "Data berhasil dihapus!")
                self.load_table()
                self.txtID_3.clear()
                self.cmbJenis_3.setCurrentIndex(0)
                self.txtNama_3.clear()
                self.cmbUkuran_3.setCurrentIndex(0)
                self.txtStok_3.clear()
                self.txtHarga_3.clear()
        except Exception as e:
            QMessageBox.critical(self.centralwidget, "Error", f"Terjadi kesalahan: {e}!")

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = back.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.centralwidget.window().close()
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())