# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tambah_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 30, 301, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 70, 411, 261))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_barang = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_barang.setGeometry(QtCore.QRect(140, 40, 230, 30))
        self.comboBox_barang.setObjectName("comboBox_barang")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_ukuran = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ukuran.setGeometry(QtCore.QRect(140, 90, 100, 30))
        self.comboBox_ukuran.setObjectName("comboBox_ukuran")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(260, 90, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_warna = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_warna.setGeometry(QtCore.QRect(310, 90, 60, 30))
        self.comboBox_warna.setObjectName("comboBox_warna")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_harga = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_harga.setGeometry(QtCore.QRect(140, 140, 150, 30))
        self.lineEdit_harga.setReadOnly(True)
        self.lineEdit_harga.setObjectName("lineEdit_harga")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinBox_jumlah = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_jumlah.setGeometry(QtCore.QRect(140, 190, 80, 30))
        self.spinBox_jumlah.setMinimum(1)
        self.spinBox_jumlah.setMaximum(100)
        self.spinBox_jumlah.setProperty("value", 1)
        self.spinBox_jumlah.setObjectName("spinBox_jumlah")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(230, 190, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_subtotal = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_subtotal.setGeometry(QtCore.QRect(310, 190, 80, 30))
        self.lineEdit_subtotal.setReadOnly(True)
        self.lineEdit_subtotal.setObjectName("lineEdit_subtotal")
        self.pushButton_simpan = QtWidgets.QPushButton(Dialog)
        self.pushButton_simpan.setGeometry(QtCore.QRect(150, 340, 100, 35))
        self.pushButton_simpan.setObjectName("pushButton_simpan")
        self.pushButton_batal = QtWidgets.QPushButton(Dialog)
        self.pushButton_batal.setGeometry(QtCore.QRect(260, 340, 100, 35))
        self.pushButton_batal.setObjectName("pushButton_batal")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tambah Barang"))
        Dialog.setStyleSheet(_translate("Dialog", "QDialog { background-color: #E3F2FD; }"))
        self.label.setStyleSheet(_translate("Dialog", "color: #0D47A1;"))
        self.label.setText(_translate("Dialog", "TAMBAH BARANG"))
        self.groupBox.setStyleSheet(_translate("Dialog", "QGroupBox { \n"
"     background-color: white; \n"
"     border: 2px solid #BBDEFB; \n"
"     border-radius: 10px; \n"
"     margin-top: 15px; \n"
"     padding-top: 15px;\n"
"     font: 700 12pt \"Times New Roman\"; \n"
"     color: #1976D2; \n"
"    }\n"
"    QGroupBox::title { \n"
"     subcontrol-origin: margin; \n"
"     subcontrol-position: top center; \n"
"     padding: 0 10px; \n"
"    }"))
        self.groupBox.setTitle(_translate("Dialog", "Pilih Barang"))
        self.label_2.setText(_translate("Dialog", "Nama Barang:"))
        self.comboBox_barang.setStyleSheet(_translate("Dialog", "QComboBox { border: 1px solid #BBDEFB; border-radius: 5px; padding: 5px; }"))
        self.label_3.setText(_translate("Dialog", "Ukuran:"))
        self.comboBox_ukuran.setStyleSheet(_translate("Dialog", "QComboBox { border: 1px solid #BBDEFB; border-radius: 5px; padding: 5px; }"))
        self.label_4.setText(_translate("Dialog", "Warna:"))
        self.comboBox_warna.setStyleSheet(_translate("Dialog", "QComboBox { border: 1px solid #BBDEFB; border-radius: 5px; padding: 5px; }"))
        self.label_5.setText(_translate("Dialog", "Harga Satuan:"))
        self.lineEdit_harga.setStyleSheet(_translate("Dialog", "QLineEdit { \n"
"      border: 1px solid #BBDEFB; \n"
"      border-radius: 5px; \n"
"      padding: 5px; \n"
"      background-color: #F5F5F5;\n"
"     }"))
        self.label_6.setText(_translate("Dialog", "Jumlah:"))
        self.spinBox_jumlah.setStyleSheet(_translate("Dialog", "QSpinBox { \n"
"      border: 1px solid #BBDEFB; \n"
"      border-radius: 5px; \n"
"      padding: 5px;\n"
"     }"))
        self.label_7.setText(_translate("Dialog", "Sub Total"))
        self.lineEdit_subtotal.setStyleSheet(_translate("Dialog", "QLineEdit { \n"
"      border: 1px solid #BBDEFB; \n"
"      border-radius: 5px; \n"
"      padding: 5px; \n"
"      background-color: #F5F5F5;\n"
"      font-weight: bold;\n"
"     }"))
        self.pushButton_simpan.setStyleSheet(_translate("Dialog", "QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 15px;\n"
"    font: 700 11pt \"Times New Roman\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #388E3C;\n"
"}"))
        self.pushButton_simpan.setText(_translate("Dialog", "Simpan"))
        self.pushButton_batal.setStyleSheet(_translate("Dialog", "QPushButton {\n"
"    background-color: #F44336;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 15px;\n"
"    font: 700 11pt \"Times New Roman\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D32F2F;\n"
"}"))
        self.pushButton_batal.setText(_translate("Dialog", "Batal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
